name: com.example.simple_app
description: A simple Flutter application with a login screen and a home screen. The app uses the Cubit pattern for state management.
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  equatable: ^2.0.3

dev_dependencies:
  bloc_test: ^8.0.0
  mocktail: ^0.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true